apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: awesome-media-backend-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: awesome-media-backend-deployment
  targetCPUUtilizationPercentage: 50
