spring:
  application:
    name: awesome-media-apigateway

server:
  port: 9999

management:
  security:
    enabled: false
    
zuul:
  ignored-services: "*"
  routes:
    awesome-media-backend: /awesome-media/**
#    awesome-media-backend:
#      path: /awesome-media/**
#      url: http://localhost:8090      

eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8791/eureka/