spring:
  application:
    name: awesome-media-discovery

server:
  port: 8791
  
management:
  security:
    enabled: false

eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    region: default
    fetch-registry: false
    register-with-eureka: false
    service-url:
     defaultZone: http://localhost:8761/eureka/
    
